-- ================================================================
-- BASE DE DATOS POKEMON
-- ================================================================

CREATE TABLE TIPOS(
    COD_TIPO NUMBER(3),
    NOMBRE VARCHAR2(30) NOT NULL,
    DEBILIDAD VARCHAR2(100),
    RESISTENCIA VARCHAR2(100),
    CONSTRAINT PK_TIPOS PRIMARY KEY (COD_TIPO),
    CONSTRAINT UQ_TIPO_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE HABILIDADES(
    COD_HABILIDAD NUMBER(4),
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    EFECTO VARCHAR2(200),
    CONSTRAINT PK_HABILIDADES PRIMARY KEY (COD_HABILIDAD),
    CONSTRAINT UQ_HABILIDAD_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE MAPA(
    COD_ZONA NUMBER(4),
    NOMBRE VARCHAR2(50) NOT NULL,
    REGION VARCHAR2(30) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    CONSTRAINT PK_MAPA PRIMARY KEY (COD_ZONA)
);

CREATE TABLE POKEMON(
    COD_POKEMON NUMBER(4),
    NOMBRE VARCHAR2(50) NOT NULL,
    PS_BASE NUMBER(3) NOT NULL,
    ATAQUE_BASE NUMBER(3) NOT NULL,
    DEFENSA_BASE NUMBER(3) NOT NULL,
    VELOCIDAD_BASE NUMBER(3) NOT NULL,
    COD_TIPO_1 NUMBER(3) NOT NULL,
    COD_TIPO_2 NUMBER(3),
    COD_HABILIDAD NUMBER(4) NOT NULL,
    COD_ZONA NUMBER(4),
    CONSTRAINT PK_POKEMON PRIMARY KEY (COD_POKEMON),
    CONSTRAINT UQ_POKEMON_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CHK_PS_BASE CHECK (PS_BASE > 0),
    CONSTRAINT CHK_ATAQUE_BASE CHECK (ATAQUE_BASE > 0),
    CONSTRAINT CHK_DEFENSA_BASE CHECK (DEFENSA_BASE > 0),
    CONSTRAINT CHK_VELOCIDAD_BASE CHECK (VELOCIDAD_BASE > 0),
    CONSTRAINT FK_POKEMON_TIPO1 FOREIGN KEY (COD_TIPO_1) REFERENCES TIPOS(COD_TIPO),
    CONSTRAINT FK_POKEMON_TIPO2 FOREIGN KEY (COD_TIPO_2) REFERENCES TIPOS(COD_TIPO),
    CONSTRAINT FK_POKEMON_HABILIDAD FOREIGN KEY (COD_HABILIDAD) REFERENCES HABILIDADES(COD_HABILIDAD),
    CONSTRAINT FK_POKEMON_ZONA FOREIGN KEY (COD_ZONA) REFERENCES MAPA(COD_ZONA)
);

CREATE TABLE MOVIMIENTOS(
    COD_MOVIMIENTO NUMBER(4),
    NOMBRE VARCHAR2(50) NOT NULL,
    POTENCIA NUMBER(3),
    PRECISION_MOV NUMBER(3),
    PP NUMBER(2) NOT NULL,
    CATEGORIA VARCHAR2(20) NOT NULL,
    COD_TIPO NUMBER(3) NOT NULL,
    CONSTRAINT PK_MOVIMIENTOS PRIMARY KEY (COD_MOVIMIENTO),
    CONSTRAINT UQ_MOVIMIENTO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CHK_POTENCIA CHECK (POTENCIA >= 0),
    CONSTRAINT CHK_PRECISION CHECK (PRECISION_MOV BETWEEN 0 AND 100),
    CONSTRAINT CHK_PP CHECK (PP > 0),
    CONSTRAINT CHK_CATEGORIA CHECK (UPPER(CATEGORIA) IN ('FISICO', 'ESPECIAL', 'ESTADO')),
    CONSTRAINT FK_MOVIMIENTO_TIPO FOREIGN KEY (COD_TIPO) REFERENCES TIPOS(COD_TIPO)
);

CREATE TABLE OBJETOS(
    COD_OBJETO NUMBER(4),
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(300),
    PRECIO NUMBER(6) NOT NULL,
    EFECTO VARCHAR2(200),
    CONSTRAINT PK_OBJETOS PRIMARY KEY (COD_OBJETO),
    CONSTRAINT UQ_OBJETO_NOMBRE UNIQUE (NOMBRE),
    CONSTRAINT CHK_PRECIO CHECK (PRECIO >= 0)
);

CREATE TABLE ENTRENADOR(
    COD_ENTRENADOR NUMBER(6),
    NOMBRE VARCHAR2(80) NOT NULL,
    DNI VARCHAR2(20) NOT NULL,
    COD_ZONA NUMBER(4),
    CONSTRAINT PK_ENTRENADOR PRIMARY KEY (COD_ENTRENADOR),
    CONSTRAINT UQ_ENTRENADOR_DNI UNIQUE (DNI),
    CONSTRAINT FK_ENTRENADOR_ZONA FOREIGN KEY (COD_ZONA) REFERENCES MAPA(COD_ZONA)
);